default: TCS.py TRS.py user.py
	chmod +x TCS.py
	chmod +x TRS.py
	chmod +x user.py
	rm languages.txt; true
	cp -v TRS.py englishTRS/
	cp -v TRS.py frenchTRS/

clean:
	rm languages.txt; true
	rm englishTRS/TRS.py; true
	rm frenchTRS/TRS.py; true